import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Container from "@/components/ui/Container";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Creative Hub IT Agency",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-sm md:text-base`}
      >
        <header>
          <Container className="max-w-291.75 fixed top-10 left-[50%] -translate-x-[50%]">
            <Navbar />
          </Container>
        </header>
        <main className="space-y-16 md:space-y-20 min-h-[80dvh]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
